apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Service
metadata:
  name: session-gate
  namespace: dev
spec:
  selector:
    app: session-gate
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: session-gate
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: session-gate
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: session-gate
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - create
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: session-gate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: session-gate
subjects:
  - kind: ServiceAccount
    name: session-gate
    namespace: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-gate
  namespace: dev
  labels:
    app: session-gate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-gate
  template:
    metadata:
      labels:
        app: session-gate
    spec:
      serviceAccountName: session-gate
      containers:
        - name: session-gate
          image: docker.io/warmmetal/session-gate:0.1.0
          ports:
            - containerPort: 8001