// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package session

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	// optional
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Hostpath             []string `protobuf:"bytes,3,rep,name=hostpath,proto3" json:"hostpath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *App) GetHostpath() []string {
	if m != nil {
		return m.Hostpath
	}
	return nil
}

type TerminalSize struct {
	Width                uint32   `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalSize) Reset()         { *m = TerminalSize{} }
func (m *TerminalSize) String() string { return proto.CompactTextString(m) }
func (*TerminalSize) ProtoMessage()    {}
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *TerminalSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalSize.Unmarshal(m, b)
}
func (m *TerminalSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalSize.Marshal(b, m, deterministic)
}
func (m *TerminalSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalSize.Merge(m, src)
}
func (m *TerminalSize) XXX_Size() int {
	return xxx_messageInfo_TerminalSize.Size(m)
}
func (m *TerminalSize) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalSize.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalSize proto.InternalMessageInfo

func (m *TerminalSize) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *TerminalSize) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type OpenAppRequest struct {
	App                  *App          `protobuf:"bytes,1,opt,name=App,proto3" json:"App,omitempty"`
	Stdin                []string      `protobuf:"bytes,2,rep,name=Stdin,proto3" json:"Stdin,omitempty"`
	TerminalSize         *TerminalSize `protobuf:"bytes,3,opt,name=TerminalSize,proto3" json:"TerminalSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OpenAppRequest) Reset()         { *m = OpenAppRequest{} }
func (m *OpenAppRequest) String() string { return proto.CompactTextString(m) }
func (*OpenAppRequest) ProtoMessage()    {}
func (*OpenAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *OpenAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenAppRequest.Unmarshal(m, b)
}
func (m *OpenAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenAppRequest.Marshal(b, m, deterministic)
}
func (m *OpenAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenAppRequest.Merge(m, src)
}
func (m *OpenAppRequest) XXX_Size() int {
	return xxx_messageInfo_OpenAppRequest.Size(m)
}
func (m *OpenAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenAppRequest proto.InternalMessageInfo

func (m *OpenAppRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *OpenAppRequest) GetStdin() []string {
	if m != nil {
		return m.Stdin
	}
	return nil
}

func (m *OpenAppRequest) GetTerminalSize() *TerminalSize {
	if m != nil {
		return m.TerminalSize
	}
	return nil
}

type AppResponse struct {
	Stdout               string   `protobuf:"bytes,1,opt,name=Stdout,proto3" json:"Stdout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppResponse) Reset()         { *m = AppResponse{} }
func (m *AppResponse) String() string { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()    {}
func (*AppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *AppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppResponse.Unmarshal(m, b)
}
func (m *AppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppResponse.Marshal(b, m, deterministic)
}
func (m *AppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppResponse.Merge(m, src)
}
func (m *AppResponse) XXX_Size() int {
	return xxx_messageInfo_AppResponse.Size(m)
}
func (m *AppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppResponse proto.InternalMessageInfo

func (m *AppResponse) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func init() {
	proto.RegisterType((*App)(nil), "session.App")
	proto.RegisterType((*TerminalSize)(nil), "session.TerminalSize")
	proto.RegisterType((*OpenAppRequest)(nil), "session.OpenAppRequest")
	proto.RegisterType((*AppResponse)(nil), "session.AppResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4b, 0xec, 0x30,
	0x10, 0x87, 0x5f, 0xb7, 0x6f, 0xb7, 0x76, 0x76, 0xd7, 0x43, 0xa8, 0x5a, 0xf6, 0x20, 0x4b, 0x41,
	0xe8, 0xa9, 0xc8, 0x7a, 0x12, 0x44, 0xe8, 0x49, 0xc5, 0x83, 0x90, 0x0a, 0x9e, 0xab, 0x0d, 0xdb,
	0x80, 0x4d, 0xc6, 0x66, 0xf6, 0xe2, 0xcd, 0xff, 0x5c, 0x76, 0x1a, 0x8a, 0xbd, 0xe5, 0x4b, 0x66,
	0x7e, 0xf3, 0x25, 0x81, 0xb8, 0xc7, 0x8f, 0x02, 0x7b, 0x4b, 0x56, 0x44, 0x4e, 0x39, 0xa7, 0xad,
	0xc9, 0x9e, 0x21, 0x2c, 0x11, 0x85, 0x80, 0xff, 0xa6, 0xee, 0x54, 0x1a, 0x6c, 0x83, 0x3c, 0x96,
	0xbc, 0x16, 0x09, 0xcc, 0x75, 0x57, 0xef, 0x55, 0x3a, 0xe3, 0xcd, 0x01, 0xc4, 0x06, 0x4e, 0x5a,
	0xeb, 0x08, 0x6b, 0x6a, 0xd3, 0x70, 0x1b, 0xe6, 0xb1, 0x1c, 0x39, 0xbb, 0x83, 0xd5, 0xab, 0xea,
	0x3b, 0x6d, 0xea, 0xcf, 0x4a, 0x7f, 0x73, 0xc2, 0x9b, 0x6e, 0xa8, 0xe5, 0xd8, 0xb5, 0x1c, 0x40,
	0x9c, 0xc3, 0xe2, 0x51, 0xe9, 0x7d, 0x4b, 0x1c, 0xbc, 0x96, 0x9e, 0xb2, 0x9f, 0x00, 0x4e, 0x5f,
	0x50, 0x99, 0x12, 0x51, 0xaa, 0xaf, 0x83, 0x72, 0x24, 0x2e, 0xd9, 0x8e, 0xdb, 0x97, 0xbb, 0x55,
	0xe1, 0xa5, 0x8b, 0x63, 0x05, 0x6b, 0x27, 0x30, 0xaf, 0xa8, 0xd1, 0x26, 0x9d, 0xb1, 0xc9, 0x00,
	0xe2, 0x76, 0xaa, 0x91, 0x86, 0xdc, 0x7e, 0x36, 0xb6, 0xff, 0x3d, 0x94, 0x93, 0xd2, 0xec, 0x0a,
	0x96, 0x3c, 0xde, 0xa1, 0x35, 0x4e, 0x1d, 0x55, 0x2b, 0x6a, 0xec, 0x81, 0xfc, 0xc3, 0x78, 0xda,
	0x3d, 0x41, 0x54, 0x22, 0x3e, 0xd4, 0xa4, 0xc4, 0x3d, 0x44, 0x5e, 0x5a, 0x5c, 0x8c, 0x13, 0xa6,
	0xd7, 0xd8, 0x24, 0x13, 0x73, 0x1f, 0x9e, 0xfd, 0xcb, 0x83, 0xeb, 0xe0, 0x7d, 0xc1, 0x1f, 0x72,
	0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xae, 0x8b, 0x97, 0x9d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppGateClient is the client API for AppGate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppGateClient interface {
	OpenApp(ctx context.Context, opts ...grpc.CallOption) (AppGate_OpenAppClient, error)
}

type appGateClient struct {
	cc *grpc.ClientConn
}

func NewAppGateClient(cc *grpc.ClientConn) AppGateClient {
	return &appGateClient{cc}
}

func (c *appGateClient) OpenApp(ctx context.Context, opts ...grpc.CallOption) (AppGate_OpenAppClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AppGate_serviceDesc.Streams[0], "/session.AppGate/OpenApp", opts...)
	if err != nil {
		return nil, err
	}
	x := &appGateOpenAppClient{stream}
	return x, nil
}

type AppGate_OpenAppClient interface {
	Send(*OpenAppRequest) error
	Recv() (*AppResponse, error)
	grpc.ClientStream
}

type appGateOpenAppClient struct {
	grpc.ClientStream
}

func (x *appGateOpenAppClient) Send(m *OpenAppRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *appGateOpenAppClient) Recv() (*AppResponse, error) {
	m := new(AppResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppGateServer is the server API for AppGate service.
type AppGateServer interface {
	OpenApp(AppGate_OpenAppServer) error
}

// UnimplementedAppGateServer can be embedded to have forward compatible implementations.
type UnimplementedAppGateServer struct {
}

func (*UnimplementedAppGateServer) OpenApp(srv AppGate_OpenAppServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenApp not implemented")
}

func RegisterAppGateServer(s *grpc.Server, srv AppGateServer) {
	s.RegisterService(&_AppGate_serviceDesc, srv)
}

func _AppGate_OpenApp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AppGateServer).OpenApp(&appGateOpenAppServer{stream})
}

type AppGate_OpenAppServer interface {
	Send(*AppResponse) error
	Recv() (*OpenAppRequest, error)
	grpc.ServerStream
}

type appGateOpenAppServer struct {
	grpc.ServerStream
}

func (x *appGateOpenAppServer) Send(m *AppResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *appGateOpenAppServer) Recv() (*OpenAppRequest, error) {
	m := new(OpenAppRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AppGate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "session.AppGate",
	HandlerType: (*AppGateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenApp",
			Handler:       _AppGate_OpenApp_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
